name: Deployment
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
    - uses: actions/checkout@v1
    - uses: stefanoeb/eslint-action@1.0.2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install Packages
      run: yarn install --ignore-engines
    - name: Run ESLint
      run: eslint . --ext .js,.jsx,.ts,.tsx
    - name: Test
      run: yarn test

    #  - name: Build page
    #  run: npm run build